version: 2.1

orbs:
  browser-tools: circleci/browser-tools@1.4.0

jobs:
  test-java:
    docker:
      - image: cimg/openjdk:17.0
    steps:
      - checkout
      - run:
          name: Install Chrome 124
          command: |
            sudo apt-get update
            sudo apt-get install -y wget unzip
            wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
            sudo apt install ./google-chrome-stable_current_amd64.deb
            google-chrome --version
      - run:
          name: Install Chrome 136 for Testing
          command: |
            wget https://storage.googleapis.com/chrome-for-testing-public/136.0.7103.113/linux64/chrome-linux64.zip
            unzip chrome-linux64.zip
            sudo mv chrome-linux64 /opt/google/chrome
            sudo ln -sf /opt/google/chrome/chrome /usr/bin/google-chrome
      - run:
          command: mvn install

workflows:
  build-and-test:
    jobs:
      - test-java
