version: 2.1

orbs:
  browser-tools: circleci/browser-tools@1.4.0

jobs:
  test-java:
    docker:
      - image: cimg/openjdk:17.0
    steps:
      - checkout
      - run:
          name: Install Chrome 124
          command: |
            sudo apt-get update
            sudo apt-get install -y wget unzip
            wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
            sudo apt install ./google-chrome-stable_current_amd64.deb
            google-chrome --version
      - run:
          name: Install ChromeDriver 124
          command: |
            wget https://chromedriver.storage.googleapis.com/124.0.6367.91/chromedriver_linux64.zip
            unzip chromedriver_linux64.zip
            sudo mv chromedriver /usr/local/bin/
            chromedriver --version
      - run:
          command: mvn install

workflows:
  build-and-test:
    jobs:
      - test-java
